apiVersion: v1
kind: ResourceQuota
metadata:
  name: hello-prod-quota
  namespace: hello-prod
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi
    pods: "10"
